jwt:
  header: Authorization

  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK

  # 6시간
  access-expiration-time: 21600000
  # 3일
  reissue-refresh-time: 259200000
  # 7일
  refresh-expiration-time: 604800000